### ISSUE TITLE
Magellan channel ordering issue

### ISSUE THREAD

**Issue by kdmarchuk** [henrypinkard/Pygellan#11] opened 2019-09-06 23:22 UTC
Hi Henry, 

I can elaborate more on this issue next week, but wanted you to be aware that there is some weird channel acquisition bug on the latest nightly build of Magellan. The channels don't stay consistent as far as the ordering goes; ch1, ch2, ch3 becomes ch2, ch3, ch1, or something. I wasn't able to find a pattern as I was trying to run an expt. Will get you more details soon.

I'll see you in person for the fix?
Kyle

**Comment by henrypinkard** [comment] 2019-09-09 03:11
Hey I showed up at your apartment as soon as I got this issue, but I guess you were still at work...

I found and fixed a pretty bad bug where if you aborted an acquisition it could sometimes bleed into the next one. Maybe this was the cause? If not, lmk if you can reproduce (ideally on demo config)

**Comment by kdmarchuk** [comment] 2019-09-18 23:15
This might have something to do with it. In demo, latest nightly build, the number of channels in the description doesn't reflect the number of channels checked. It's always num_checked + 1. 
![image](https://user-images.githubusercontent.com/54245002/65193316-7e5f3e80-da2f-11e9-8ef2-516f452eb65d.png)
![image](https://user-images.githubusercontent.com/54245002/65193322-861ee300-da2f-11e9-9419-0611387b4ede.png)

**Comment by henrypinkard** [comment] 2019-09-19 18:44
I decided to bite the bullet and do a major overhaul of the image display code in Magellan. I'm rewriting from scratch a lot of stuff that was previously based upon hacky imageJ/microamanger workarounds. This should make magellan much easier to maintain and add new features to, but will probably come with a lot of bugs along the way. Probably will not revisit this until that is complete

**Comment by henrypinkard** [comment] 2019-10-03 17:17
New image viewer online! https://github.com/nicost/micro-manager/pull/74

The screenshots above were just a little typo, which is now fixed.

I'm am closing this for now as the display has been completely rewritten, but if you see something similar in the future open a new issue

**Closed as completed by henrypinkard** 2019-10-03 17:17 UTC
